version: "3"

volumes:
  db_data:

services:
  node:
    build: ./node-elm
    working_dir: /code
    command: npm run dev
    volumes:
      - ./node-elm:/code
    ports:
      - "8001:8001"
    links:
      - mongo
  vue:
    build: ./vue2-elm
    working_dir: /code
    command: npm run dev
    volumes:
      - ./vue2-elm:/code
    ports:
      - "8000:8000"
  mongo:
    image: mongo:3.7
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
